export interface Project {
  slug: string;
  title: string;
  year: string;
  type: string;
  tags: string[];
  description: string;
  // images: tableau de chemins dans /public/images/graphisme/[slug]/
  images: string[];
  cover: string;
  websiteUrl?: string;
  guidelinesUrl?: string;
  instagramUrl?: string; // image de couverture pour la grille
  featured?: boolean; // mis en avant (plus grand dans la grille)
}

export const projectsGraphisme: Project[] = [
  {
    slug: "vera",
    title: "Vera",
    year: "2025",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Charte graphique", "Digital"],
    description: "VERA est une plateforme immersive qui repense la manière de présenter, partager et explorer ses créations en trois dimensions. À la croisée du web, de la scénographie virtuelle et de l'expérience interactive, elle transforme chaque présentation en un espace vivant où les objets, les œuvres et les idées prennent une nouvelle dimension. Pensée comme un véritable studio de création en ligne, VERA permet de concevoir des scènes 3D directement depuis un navigateur, sans barrières techniques ni contraintes de développement. Là où les présentations traditionnelles se limitent à des images ou des diapositives statiques, VERA offre des environnements interactifs dans lesquels les utilisateurs peuvent naviguer librement, observer chaque détail et découvrir les projets sous tous leurs angles.\n\nLe projet s'adresse aussi bien aux artistes, designers, studios créatifs, architectes ou marques souhaitant valoriser leurs créations à travers des expériences immersives. Qu'il s'agisse d'un prototype industriel, d'un objet de design, d'une œuvre d'art ou d'un portfolio créatif, chaque projet peut être mis en scène dans un showroom virtuel accessible par un simple lien.\n\nAu-delà de la visualisation, VERA encourage une approche collaborative de la création. Les utilisateurs peuvent co-concevoir des scènes en temps réel, partager leurs retours directement dans l'espace 3D et itérer instantanément sans avoir à exporter ou transférer de fichiers.\n\nL'identité visuelle de VERA traduit cette volonté d'explorer de nouveaux territoires créatifs. Son univers graphique repose sur une esthétique contemporaine et minimaliste, tout comme les services que la plateforme propose, associant noir, blanc, et un rose doux, ces contrastes créent un équilibre entre sophistication technologique et énergie créative. Les éléments graphiques s'inspirent de notions de perception, de rayonnement et de multiplicité. Les motifs de répétition évoquent la multidisciplinarité et les possibilités infinies de création. Les formes rayonnantes symbolisent la diffusion des idées et l'expansion des œuvres au-delà des espaces physiques.\n\nÀ travers cette identité, VERA se positionne comme un pont entre le réel et le virtuel. Plus qu'un simple outil de présentation, la plateforme propose une nouvelle manière de raconter les projets, de partager les processus créatifs et de vivre les œuvres, elle ouvre un espace où la technologie s'efface au profit de l'expérience, permettant aux idées de se déployer librement dans un environnement immersif, collaboratif et accessible.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957984/portfolio/images/graphisme/VERA/1_n2nox4.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782958004/portfolio/images/graphisme/VERA/2_ixmwej.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958006/portfolio/images/graphisme/VERA/3_ryfeew.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782958008/portfolio/images/graphisme/VERA/4_gihbrv.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958010/portfolio/images/graphisme/VERA/5_pkdi3g.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958011/portfolio/images/graphisme/VERA/6_kcjqlm.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958012/portfolio/images/graphisme/VERA/7_bevmx5.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782958015/portfolio/images/graphisme/VERA/8.2_pdp1xw.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958017/portfolio/images/graphisme/VERA/8_y39y8f.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983269/portfolio/images/graphisme/VERA/9_omihho.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957984/portfolio/images/graphisme/VERA/10_qgkris.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957985/portfolio/images/graphisme/VERA/11_y87igb.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957987/portfolio/images/graphisme/VERA/12_ptpcvx.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957986/portfolio/images/graphisme/VERA/12.2_ywvfsr.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957990/portfolio/images/graphisme/VERA/13_z406w6.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782957992/portfolio/images/graphisme/VERA/14_d6r6ub.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957993/portfolio/images/graphisme/VERA/15_q3oo77.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983267/portfolio/images/graphisme/VERA/16_mrwmgi.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957999/portfolio/images/graphisme/VERA/17_gaewv0.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782958001/portfolio/images/graphisme/VERA/18_qsvots.mp4",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782958124/portfolio/images/graphisme/vera2_ih9tth.png",
    featured: true,
  },
  {
    slug: "bloomist",
    title: "Bloomist",
    year: "2025",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Charte graphique"],
    description: "Bloomist est un service d'abonnement de café conçu pour les passionnés de café qui souhaitent explorer des saveurs du monde entier. Chaque mois, Bloomist livre des grains fraîchement torréfiés provenant de différentes régions, offrant une expérience unique aux clients pour découvrir les origines et les notes de dégustation de chaque café. Avec un accent sur la durabilité, tous les emballages sont écologiques, et chaque achat soutient les petites exploitations caféières à travers le monde. La direction artistique de Bloomist joue sur la tension entre le terroir et l'éditorial. La palette se construit autour d'un bordeaux violacé, d'un vert forêt, un rouge vif et d'un vert pastel, des teintes organiques inspirées de la nature et du caféier lui-même qui ancrent la marque dans le monde végétal. Le logo, une forme botanique stylisée elle aussi tirée caféier, oscille entre l'illustration d'herbier et l'emblème de maison. La typographie est volontairement large, elle prend toute la place comme les armes du café en bouche, une présence forte mais subtile, pour ancrer l'identité et contraster avec la douceur et le flou des matières photographiées. L'ensemble évoque une esthétique des années 70 revisitée, la rigueur de l'éditorial avec le goût chaleureux et nostalgique du café.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957767/portfolio/images/graphisme/Bloomist/1_coqgzg.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983160/portfolio/images/graphisme/Bloomist/2_snocik.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983167/portfolio/images/graphisme/Bloomist/3_zncayy.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957778/portfolio/images/graphisme/Bloomist/4_yngrey.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983169/portfolio/images/graphisme/Bloomist/5_pcvugw.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983172/portfolio/images/graphisme/Bloomist/6_ianjrs.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983175/portfolio/images/graphisme/Bloomist/7_mxlr7r.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983177/portfolio/images/graphisme/Bloomist/8_uqhavi.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957790/portfolio/images/graphisme/Bloomist/9_bxlkxi.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782957769/portfolio/images/graphisme/Bloomist/10_ai0x6g.mp4",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782983179/portfolio/images/graphisme/Bloomist_ilfb6o.png",
    featured: true,
  },
  {
    slug: "cera",
    title: "Cëra",
    year: "2024",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Identité visuelle"],
    description: "Cachée dans une allée fleurie, la boutique de céramiques \"Cera\" attire les passants avec ses vitrines élégantes. Chaque pièce, fabriquée avec précision et passion, raconte une histoire unique. Les visiteurs sont séduits par les designs modernes et les couleurs vibrantes, repartant avec une œuvre artisanale stylée et une expérience mémorable. La direction artistique de Cëra construit sa singularité sur un contraste inattendu : un vert jaune acide, confronté à un brun chocolat profond et un rose doux. Ces deux couleurs s'opposent et se complètent, elles évoquent à la fois la terre dont naissent les céramiques et la vitalité d'une boutique pleine de vie. Le logotype porte lui-même sa marque, le tréma sur le ë, signature discrète qui fait de l'ordinaire quelque chose d'unique, à l'image de chaque pièce vendue. Des ornements calligraphiques viennent ponctuer l'ensemble, une touche de douceur florale dans une direction par ailleurs très construite et très brute.\n\nLe projet Cëra est un projet fictif, et répond au brief du RVB Challenge de Myriam Phung et Solen Daligny. Un brief mensuel pour enrichir et développer son portfolio (la preuve en est, ça marche).",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958022/portfolio/images/graphisme/ce%CC%88ra/1_hfotdd.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958030/portfolio/images/graphisme/ce%CC%88ra/2_wtpfwj.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958032/portfolio/images/graphisme/ce%CC%88ra/3_iqnsln.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958034/portfolio/images/graphisme/ce%CC%88ra/4_lyzhj7.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958036/portfolio/images/graphisme/ce%CC%88ra/5_l8adpg.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958038/portfolio/images/graphisme/ce%CC%88ra/6_atr4eu.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958041/portfolio/images/graphisme/ce%CC%88ra/7_zulnne.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983273/portfolio/images/graphisme/ce%CC%88ra/8_pbkegv.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983275/portfolio/images/graphisme/ce%CC%88ra/9_cpd747.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958024/portfolio/images/graphisme/ce%CC%88ra/10_fuqpeh.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983271/portfolio/images/graphisme/ce%CC%88ra/11_mrn9xb.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958027/portfolio/images/graphisme/ce%CC%88ra/12_gmdl33.png",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782958051/portfolio/images/graphisme/ce%CC%88ra_hhwkro.png",
    featured: true,
  },
  {
    slug: "amorcita",
    title: "Amorcita",
    year: "2025",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Charte graphique"],
    description: "Amorcita est une marque de bijoux artisanaux que je connais depuis longtemps, depuis plus de quinze ans pour être exacte. Je croise ses créations sur le marché de Locquirec et j'ai toujours été fascinée par l'énergie solaire de sa créatrice, capable de rassembler naturellement les gens autour de son univers et surtout de son stand. Lorsque l'occasion s'est présentée de concevoir l'identité de la marque, il était essentiel pour moi de retranscrire cette personnalité chaleureuse, spontanée et lumineuse jusque dans les moindres détails.\n\nLe projet a consisté à imaginer un univers graphique complet, pensé comme le prolongement de son artisanat : une identité douce et vivante, mêlant couleurs chaleureuses, inspirations méditerranéennes, pampilles, textures et références au fait main. Chaque élément visuel a été conçu pour refléter la dimension solaire, coloré des bijoux et le lien qu'ils créent avec celles et ceux qui les portent.\n\nAu-delà du branding, j'ai également conçu et développé l'expérience e-commerce de la marque et le site boutique. Une attention particulière a été portée à la personnalisation des bijoux gravés grâce à la mise en place d'un système sur mesure permettant de choisir le nombre de médailles, de renseigner les gravures recto et verso de chacune d'entre elles et d'ajouter des indications spécifiques directement depuis la fiche produit. L'objectif était de rendre la personnalisation aussi simple et intuitive que possible tout en préservant l'univers sensible de la marque.\n\nCe projet a également été l'occasion d'un travail collaboratif autour de la stratégie de marque et de la direction esthétique avec Guillemette Levron Menou. Les photographies ont été réalisées par Jeanne Dagron.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957732/portfolio/images/graphisme/Amorcita/1_nlrnfv.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957750/portfolio/images/graphisme/Amorcita/2_zcyugq.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957753/portfolio/images/graphisme/Amorcita/3_xvm3hs.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957755/portfolio/images/graphisme/Amorcita/4_npm1fw.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957756/portfolio/images/graphisme/Amorcita/5_luxf1r.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983137/portfolio/images/graphisme/Amorcita/6_yw3szm.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957760/portfolio/images/graphisme/Amorcita/7_kwbchc.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983148/portfolio/images/graphisme/Amorcita/8_yzurwt.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957764/portfolio/images/graphisme/Amorcita/9_jsirn9.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957735/portfolio/images/graphisme/Amorcita/10_jmboex.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983121/portfolio/images/graphisme/Amorcita/11_eveaxz.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957740/portfolio/images/graphisme/Amorcita/12_ywg88h.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957742/portfolio/images/graphisme/Amorcita/13_xotqnh.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957745/portfolio/images/graphisme/Amorcita/14_mtocgy.png",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782957766/portfolio/images/graphisme/Amorcita_hpwvcg.png",
    websiteUrl: "https://www.amorcita.fr",
    instagramUrl: "https://www.instagram.com/amorcita.bijoux/?hl=fr",
    guidelinesUrl: "https://www.figma.com/proto/9MQOoNPBEGfcOmpDLDZOSF/Brand-Guidelines-Amorcita?node-id=1-2&p=f&t=GboB9iUjFar169Lp-0&scaling=contain&content-scaling=fixed&page-id=0%3A1",
    featured: true,
  },
  {
    slug: "paratente",
    title: "Paratente",
    year: "2025",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Charte graphique", "Upcycling"],
    description: "Paratente est un projet imaginé par Cléa Perez, Marie Coualan, Chloé Descombes et Gilles Rabet, étudiant.e.s à Centrale Marseille, qui transforme d'anciennes voiles de parapente en tentes légères et modulables capables de se replier en sac à dos. Pensé dans une démarche d'upcycling, le projet donne une seconde vie à des matériaux destinés à être jetés en les intégrant dans un produit fonctionnel, durable et adapté à l'itinérance. Plusieurs phases de prototypage ont permis d'affiner le concept afin de concevoir un système de pliage intuitif, rapide et compact, conciliant confort d'utilisation et légèreté. J'ai accompagné le projet à travers la création de son identité visuelle et de sa direction artistique. Le travail de branding s'est construit autour des notions de sûreté et de confiance, en valorisant la technique simple du produit. L'univers graphique met en avant la transformation de la voile de parapente, les principes de modularité et l'esprit outdoor qui caractérisent Paratente. Le produit a été conçu dans ses moindres détails, avec des systèmes de rangement et de fermeture intégrés aussi bien dans sa configuration sac à dos que dans sa configuration tente, offrant une expérience polyvalente et pratique à chaque étape de son utilisation.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983252/portfolio/images/graphisme/Paratente/1_khdd8s.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782957947/portfolio/images/graphisme/Paratente/2_wj8sol.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957950/portfolio/images/graphisme/Paratente/3_b7otjz.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957952/portfolio/images/graphisme/Paratente/4_nnur3s.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957953/portfolio/images/graphisme/Paratente/5_yhfzdp.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782957957/portfolio/images/graphisme/Paratente/6_czfqdb.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957959/portfolio/images/graphisme/Paratente/7_tbh4ni.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957963/portfolio/images/graphisme/Paratente/8_t04wut.png",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782957941/portfolio/images/graphisme/PARATENTE_w5zasu.png",
  },
  {
    slug: "kizuna",
    title: "Kizuna",
    year: "2025",
    type: "Branding",
    tags: ["Logotype", "Branding", "Animation"],
    instagramUrl: "https://www.instagram.com/kizunaprojects/?hl=fr",
    description: "Kizuna c'est une marque créée par Kizuame, un projet qui est né en 2022, mais qui a pris forme en 2025 quand on s'est associés pour travailler autour de sa marque. Kizuna est un mot japonais signifiant « liens entre les personnes », une signification qui a donné corps au logo de la marque. Le projet défend le lien qui se tisse entre les gens par le vêtement, le sentiment d'appartenance à un groupe et à son esthétique, et le rapprochement qui se crée quand on se reconnaît dans le style de quelqu'un d'autre. Cette sympathie brute prend forme dans la simplicité et la brutalité de la direction artistique. J'ai créé le logo, le branding et l'animation de celui-ci, le reste est entre les mains talentueuses de Kizuame.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983294/portfolio/images/graphisme/kizuna/1_gzqt05.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983301/portfolio/images/graphisme/kizuna/2_knxk27.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782958099/portfolio/images/graphisme/kizuna/3_pnwc3i.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983303/portfolio/images/graphisme/kizuna/4_atatvi.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958105/portfolio/images/graphisme/kizuna/5_anxzty.jpg",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958107/portfolio/images/graphisme/kizuna/6_rk7ty7.jpg",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983305/portfolio/images/graphisme/kizuna/7_hsd3qn.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958112/portfolio/images/graphisme/kizuna/8_rccmmr.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983308/portfolio/images/graphisme/kizuna/9_c90gev.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983296/portfolio/images/graphisme/kizuna/10_yqlgah.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782983298/portfolio/images/graphisme/kizuna/11_hmgo1z.mp4",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782958091/portfolio/images/graphisme/kizuna/12_itswsd.mp4",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782957919/portfolio/images/graphisme/Kizuna_cio8yh.jpg",
  },
  {
    slug: "glm",
    title: "GLM",
    year: "2025",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Identité visuelle", "Print"],
    websiteUrl: "https://guillemettelm.fr/",
    instagramUrl: "https://www.instagram.com/guillemettelm/?hl=fr",
    description: "GLM est l'identité visuelle que j'ai conçue pour Guillemette Levron-Menou, consultante en stratégie et stylisme de marque basée à Rennes, qui accompagne des entrepreneurs, boutiques et lieux d'hospitalité à révéler leur potentiel esthétique et commercial.\n\nL'enjeu était de traduire visuellement une approche à la fois humaine, stratégique et esthétique, sensible mais structurée. L'identité repose sur une palette élégante et singulière, associée à une typographie soignée qui oscille entre sérieux et douceur. Le logo, décliné en version animée, traduit une légèreté et un ensemble cohérents avec la promesse de Guillemette : redonner de l'élan.\n\nL'ensemble crée un univers de marque désirable et mémorable, à l'image de ce que Guillemette construit pour ses propres clients.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957831/portfolio/images/graphisme/GLM/1_wi1m5x.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983221/portfolio/images/graphisme/GLM/2_gvnpqu.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957876/portfolio/images/graphisme/GLM/3_ndxit7.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957877/portfolio/images/graphisme/GLM/4_m6nnce.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983227/portfolio/images/graphisme/GLM/5_xhhjeb.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957881/portfolio/images/graphisme/GLM/6_sskdur.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957884/portfolio/images/graphisme/GLM/7_vutrau.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957886/portfolio/images/graphisme/GLM/8_x7zrke.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983229/portfolio/images/graphisme/GLM/9_t3kh0x.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983208/portfolio/images/graphisme/GLM/10_mvvfnu.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957835/portfolio/images/graphisme/GLM/11_ahwiau.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957837/portfolio/images/graphisme/GLM/12_mqleic.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983210/portfolio/images/graphisme/GLM/13_ffyxrz.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957841/portfolio/images/graphisme/GLM/14_hpu1nq.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983214/portfolio/images/graphisme/GLM/15_sjijij.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957847/portfolio/images/graphisme/GLM/16_bbrc2d.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983215/portfolio/images/graphisme/GLM/17_m3keya.jpg",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983216/portfolio/images/graphisme/GLM/18_odij6c.jpg",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983218/portfolio/images/graphisme/GLM/19_jznk4h.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957860/portfolio/images/graphisme/GLM/20_bfpl2d.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782957865/portfolio/images/graphisme/GLM/21_zuckn5.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983223/portfolio/images/graphisme/GLM/22_fnfsnu.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983225/portfolio/images/graphisme/GLM/23_bslkzn.jpg",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957875/portfolio/images/graphisme/GLM/24_vojf9v.jpg",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782983232/portfolio/images/graphisme/GLM_aq7zoh.png",
  },
  {
    slug: "inkverse",
    title: "Inkverse",
    year: "2025",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Charte graphique", "Digital"],
    description: "Inkverse est une marque de papeterie créée pour les artistes et illustrateurs à la recherche d'outils inspirants et de qualité, des carnets de croquis aux encres spéciales, Inverse propose du matériel qui dynamise le processus créatif et encourage les artistes à laisser cours à leur imagination. Pour moi inkverse, c'est un univers riche, un savoir-faire certain et surtout ancien, ça évoque le papier épais, l'odeur des nouveaux carnets et de l'encre, les motifs se rapprochent aussi du papier peint presque super épais des vieilles bibliothèques. La chouette, quant à elle, raconte les nuits blanches créatives, le fait de veiller tard emporté par l'inspiration, et surtout une certaine sagesse, parce que quand on choisit inkverse on fait le choix de la qualité et de la durabilité. Parce que chaque carnet est fabriqué avec du papier recyclé, parce que l'amour du papier ne peut pas se faire au détriment de ce qu'il y a dehors. Les couleurs sont généreuses et engageantes, mais également différenciantes des couleurs très saturées qu'on retrouve beaucoup dans la papeterie ces derniers temps. Aubergine, orange brûlé, rose terracotta, vert mousse, des teintes existent dans les vieux papiers peints, dans les jardins en automne, dans les devantures de librairies. Les motifs floraux et botaniques qui recouvrent chaque visuel raconte le savoir-faire de ceux qui ont fait du beau avant nous.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958056/portfolio/images/graphisme/inkverse/1_yxxvmp.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983277/portfolio/images/graphisme/inkverse/2_e4bdj4.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983280/portfolio/images/graphisme/inkverse/3_feipc3.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782958065/portfolio/images/graphisme/inkverse/4_lm4v1w.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983282/portfolio/images/graphisme/inkverse/5_epk9ls.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983284/portfolio/images/graphisme/inkverse/6_gym4js.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983287/portfolio/images/graphisme/inkverse/7_tcjetl.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983289/portfolio/images/graphisme/inkverse/8_fpxlpe.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983291/portfolio/images/graphisme/inkverse/9_e36gvt.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782958058/portfolio/images/graphisme/inkverse/10_m3fedj.mp4",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782983238/portfolio/images/graphisme/InkVerse_fz2dde.png",
  },
  {
    slug: "casa-tierra",
    title: "Casa Tierra",
    year: "2025",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Identité visuelle", "Print"],
    description: "Casa Tierra est l'identité visuelle complète d'un stand fictif de food festival conçu pour représenter la cuisine mexicaine dans le cadre d'un festival gastronomique international près de Marseille.\n\nLe parti pris graphique est assumé et généreux : une palette directement inspirée des couleurs du Mexique, ses marchés, ses façades, sa végétation. L'illustration joue sur un mélange entre silhouettes plates et découpées d'ingrédients emblématiques et des photos réelles et gourmandes de ces mêmes aliments, créant une tension graphique entre le brut et le stylisé. Le logo custom, aux lettres irrégulières et expressives soulignées d'un soleil en éclat, évoque à la fois la chaleur du piment et l'énergie d'un festival.\n\nL'identité a été déclinée sur l'ensemble des supports du stand : affiches, menu, carte de visite, sacs, boîtes de livraison, barquettes food, banderoles, chaises longues et stand complet.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957794/portfolio/images/graphisme/Casa%20Tierra/1_al7gsy.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957810/portfolio/images/graphisme/Casa%20Tierra/2_bu66ae.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983190/portfolio/images/graphisme/Casa%20Tierra/2.2_k1yws2.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983192/portfolio/images/graphisme/Casa%20Tierra/3_sl1f3r.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983195/portfolio/images/graphisme/Casa%20Tierra/4_ko4cw7.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983198/portfolio/images/graphisme/Casa%20Tierra/5_evhxt2.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983201/portfolio/images/graphisme/Casa%20Tierra/6_nryxkr.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983203/portfolio/images/graphisme/Casa%20Tierra/7_rghhou.jpg",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957825/portfolio/images/graphisme/Casa%20Tierra/8_volxd0.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957827/portfolio/images/graphisme/Casa%20Tierra/9_iprxhb.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983182/portfolio/images/graphisme/Casa%20Tierra/10_mma6sr.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957799/portfolio/images/graphisme/Casa%20Tierra/11_qlklru.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983184/portfolio/images/graphisme/Casa%20Tierra/12_akh2t7.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983187/portfolio/images/graphisme/Casa%20Tierra/13_kigglj.png",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782983205/portfolio/images/graphisme/Casa_Tierra_vxvdoo.png",
  },
  // — Projets secondaires —
  {
    slug: "greendex",
    title: "Greendex",
    year: "2024",
    type: "Branding & identité visuelle",
    tags: ["Logotype", "Identité visuelle", "Digital"],
    description: "GreenDex est une application mobile gamifiée conçue pour encourager les 18-25 ans à explorer et (re)découvrir la nature. Grâce à l'IA et la géolocalisation, elle transforme chaque sortie en aventure. Photographier animaux et plantes rapporte de l'XP, des badges et permet de se mesurer à ses amis via un leaderboard, des objectifs journaliers et une carte interactive.\n\nSur ce projet étudiant, j'ai pris en charge le logo, le graphisme, le motion et l'illustration, en collaboration avec une équipe en charge du webdesign et du concept produit.\n\nL'identité visuelle repose sur un univers nature et jeu, les badges de collection constituent la pièce maîtresse du système graphique, chaque espèce découverte (lapin, papillon, scarabée, ortie...) est illustrée à la main, dans un style accessible et chaleureux. La typographie arrondie et organique du logotype greendex renforce le côté naturel et aventurier de l'ensemble.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957896/portfolio/images/graphisme/Greendex/1_i9auet.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957898/portfolio/images/graphisme/Greendex/2_ntbi7t.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957900/portfolio/images/graphisme/Greendex/3_eexhgl.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957901/portfolio/images/graphisme/Greendex/4_rxfgnh.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782957904/portfolio/images/graphisme/Greendex/5_kxces9.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957906/portfolio/images/graphisme/Greendex/6_shnldd.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983234/portfolio/images/graphisme/Greendex/7_h8g5x2.png",
      "https://res.cloudinary.com/kust8hzr/video/upload/v1782957911/portfolio/images/graphisme/Greendex/8_itiqcq.mp4",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983236/portfolio/images/graphisme/Greendex/9_h7csjw.png",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782958053/portfolio/images/graphisme/greendex_azn3nz.png",
  },
  {
    slug: "nuit-de-licart",
    title: "Nuit de l'ICART",
    year: "2023",
    type: "Direction artistique · Identité visuelle",
    tags: ["Affiche", "Direction artistique", "Événement"],
    description: "Direction artistique et identité visuelle pour la Nuit de l'ICART, soirée pluridisciplinaire annuelle organisée et pensée de bout en bout par les étudiants de l'ICART. Le temps d'une soirée, le campus se transforme en salles événementielles avec concert, dj set, vidéo, exposition, stand up et performances live, dans un espace pensé comme un véritable lieu d'exposition éphémère.\n\nPour cette édition organisée par Equinoxe, l'identité graphique s'est construite autour d'un visuel fluide et organique, entre matière liquide, expression et lumière néon.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983241/portfolio/images/graphisme/Nuit_de_licart/1_wapf49.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983243/portfolio/images/graphisme/Nuit_de_licart/2_dpzwnl.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957929/portfolio/images/graphisme/Nuit_de_licart/3_qlb1bk.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983245/portfolio/images/graphisme/Nuit_de_licart/4_uvrrb8.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983247/portfolio/images/graphisme/Nuit_de_licart/5_viiui3.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957935/portfolio/images/graphisme/Nuit_de_licart/6_wlxm8k.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983250/portfolio/images/graphisme/Nuit_de_licart/7_hcwqqr.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957939/portfolio/images/graphisme/Nuit_de_licart/8_sonwc0.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957940/portfolio/images/graphisme/Nuit_de_licart/9_xmdflw.png",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782958120/portfolio/images/graphisme/nuit_de_licart2_eayl3f.png",
  },
  {
    slug: "sense-2023",
    title: "Sense",
    year: "2023",
    type: "Affiche · Typographie",
    tags: ["Affiche", "Typographie custom"],
    description: "SENSE est un projet d'affiche typographique née d'un exercice imposé, composer un mot de cinq lettres en cinq caractères tous uniques, dessinés à la main. J'ai choisi le mot « sense », sens en anglais, mais aussi proche de sensé en français, pour évoquer le sens caché, le langage et les messages que portent les fleurs depuis des siècles, le floriographie, cet art où chaque espèce devient un message. L'attribution d'une symbolique aux fleurs et aux plantes remonte à l'Antiquité, à cette époque, la signification donnée aux fleurs correspond surtout à la morale, des symboles autour de la religion, de la mythologie ou du folklore. La typographie, volontairement organique et sobre, s'inspire des tiges, des courbes et des pétales. Ce choix fait écho au propos de l'affiche, la nature comme vecteur de communication, le design plus subtil et plus ancien que les mots eux-mêmes.\n\nLe message se construit entièrement à travers cinq fleurs choisies avec soin, chacune associée à une lettre du mot et à une signification précise.",
    images: [
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957964/portfolio/images/graphisme/SENSE/1_dwl5m9.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983258/portfolio/images/graphisme/SENSE/2_mdvjng.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957970/portfolio/images/graphisme/SENSE/3_jhf7e2.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782983261/portfolio/images/graphisme/SENSE/4_gcu5nd.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957974/portfolio/images/graphisme/SENSE/5_b5brwp.png",
      "https://res.cloudinary.com/kust8hzr/image/upload/v1782957977/portfolio/images/graphisme/SENSE/6_omnytr.png",
    ],
    cover: "https://res.cloudinary.com/kust8hzr/image/upload/v1782957982/portfolio/images/graphisme/SENSE_festdw.png",
  },
];
